export const DATABASE_CONNECTION = 'DATABASE_CONNECTION';

export const USER_MODEL = 'USER_MODEL';
export const TEAM_MODEL = 'TEAM_MODEL';
export const SPONSOR_MODEL = 'SPONSOR_MODEL';
export const COACH_MODEL = 'COACHE_MODEL';
export const ARTICLE_MODEL = 'ARTICLE_MODEL';
export const ARTICLE_CATEGORY_MODEL = 'ARTICLE_CATEGORY_MODEL';
export const HVW_CLASS_MODEL = 'HVW_CLASS_MODEL';
export const HVW_TABLE_MODEL = 'HVW_TABLE_MODEL';
export const HVW_WEEK_MODEL = 'HVW_WEEK_MODEL';
export const HVW_GAME_MODEL = 'HVW_GAME_MODEL';
export const HVW_CACHING_RESULT_MODEL = 'HVW_CACHING_RESULT_MODEL';
export const HVW_JOB_MODEL = 'HVW_JOB_MODEL';
export const IMAGE_MODEL = 'IMAGE_MODEL';
export const IMAGE_TAG_MODEL = 'IMAGE_TAG_MODEL';
export const CONTACT_PERSON_MODEL = 'CONTACT_PERSON_MODEL';
export const CONTACT_PERSON_CATEGORY_MODEL = 'CONTACT_PERSON_CATEGORY_MODEL';
export const FILE_MODEL = 'FILE_MODEL';
export const FILE_CATEGORY_MODEL = 'FILE_CATEGORY_MODEL';

export const FEATURE_TYPE = 'FEATURE_TYPE';
export const FEATURE_EXCEPTION_CONFIG = 'FEATURE_EXCEPTION_CONFIG';
